### ISSUE TITLE
Notification settings need to be nerfed.

### ISSUE THREAD

**Issue by FlaggedBrad** [fluffingtons/fulldark#6]
![image](https://cloud.githubusercontent.com/assets/18545011/25862128/cf26ec64-349b-11e7-99ad-0a5c16ad8f39.png)

Here are my installed thingies:
![image](https://cloud.githubusercontent.com/assets/18545011/25862165/f737c200-349b-11e7-934d-57def4f70a49.png)
![image](https://cloud.githubusercontent.com/assets/18545011/25862173/00ad1d9e-349c-11e7-80ff-7d78b856b386.png)

**Comment by ItsiAdam** [comment]
A little birdy tells me full dark 2.0 is coming very soon and that all problems will be fixed with it.
